### PR TITLE
Fix start flow action being broken for IVR flows

### PR DESCRIPTION
**Pull request by nicpottier**
Good old passing None then testing against array case..

### CODE REVIEW

**Comment by nicpottier** [comment]
review?

**Comment by ericnewcomer** [comment]
Sorry, wasn't logged in. So what was the failure? Were we trying to append to started_flows further down? None vs. empty list condition?

**Comment by ericnewcomer** [comment]
Test looks good

**Comment by nicpottier** [comment]
Ya, problem was ivr_flow wasn't passing in started_flows, and we weren't dealing with the None case.

**Pull request merged**
