### PR TITLE
Creation of new indexes to Channel model as solution of issue #300

### PR DESCRIPTION
**Pull request by Cloves23**
New indexes to solve issue [#300](https://github.com/nyaruka/mailroom/issues/300) that treats about the concurrent event misbehaving.

The new indexes created correspond to the following SQL:
```sql
CREATE INDEX "channels_conn_ch_id_status_idx" ON "channels_channelconnection" ("channel_id", "status");
CREATE INDEX "channels_conn_external_id_idx" ON "channels_channelconnection" ("channel_id", "connection_type", "external_id");
```

### CODE REVIEW

**Comment by nicpottier** [comment]
How does this solve the issue? Why two indexes? If this is just about IVR calls can't we use a partial index to reduce the size of it? We need some more details as to what is occurring here including a unit test that is reproducing the problem so we have confidence it is well understood and the fix is accurate.

**Comment by Cloves23** [comment]
> How does this solve the issue? Why two indexes? If this is just about IVR calls can't we use a partial index to reduce the size of it? We need some more details as to what is occurring here including a unit test that is reproducing the problem so we have confidence it is well understood and the fix is accurate.

Hi, @nicpottier.

Both indexes was created because of the high CPU usage of the database. In some moments reaches in 100%.

To leave no doubt, this indexes are only **part of the solution**. The complete fix demands changes on Mailroom.
The indexes give support to the corresponding queries:

### Active connection
#### [Query:](https://github.com/nyaruka/mailroom/blob/241ffded0b6aa8f5ca196c695003165ff56a6211/models/channel_connection.go#L458)
```sql
SELECT count(*)
  FROM channels_channelconnection
 WHERE channel_id = $1
   AND (status = 'W' OR status = 'R' OR status = 'I')
```

#### Partial Index:
```sql
CREATE INDEX "channels_conn_ch_id_status_idx" ON "channels_channelconnection" ("channel_id", "status")
       WHERE "channels_channelconnection"."status" IN ('W', 'R', 'I');
```

### Connections by External ID
#### [Query:](https://github.com/nyaruka/mailroom/blob/4b5298235f4f4673e3aa517d33cff3f68ff62571/models/channel_connection.go#L228)
```sql
SELECT cc.id as id, 
       cc.created_on as created_on, 
       cc.modified_on as modified_on, 
       cc.external_id as external_id,  
       cc.status as status, 
       cc.direction as direction, 
       cc.started_on as started_on, 
       cc.ended_on as ended_on, 
       cc.connection_type as connection_type, 
       cc.duration as duration, 
       cc.retry_count as retry_count, 
       cc.next_attempt as next_attempt, 
       cc.channel_id as channel_id, 
       cc.contact_id as contact_id, 
       cc.contact_urn_id as contact_urn_id, 
       cc.org_id as org_id, 
       cc.error_count as error_count, 
       fsc.flowstart_id as start_id
  FROM channels_channelconnection as cc
       LEFT OUTER JOIN flows_flowstart_connections fsc ON cc.id = fsc.channelconnection_id
 WHERE cc.channel_id = $1
   AND cc.connection_type = $2
   AND cc.external_id = $3
```

#### Partial Index:
```sql
CREATE INDEX "channels_conn_external_id_idx" ON "channels_channelconnection" ("channel_id", "external_id")
       WHERE "channels_channelconnection"."connection_type" = 'V';
```

**Comment by nicpottier** [comment]
@Cloves23 If this is only part of the solution can you open a PR on mailroom for the other side of this so we can understand what your end goal is? Thanks.

**Comment by Cloves23** [comment]
Due to the latest update, the solution will be dropped. Thanks to everyone who tried to help.

**Pull request closed without merging**
