### PR TITLE
Give every workspace a default team with access to all topics

### PR DESCRIPTION
**Pull request by rowanseymour**
Where am going with this...

 * Every workspace will have a system team called `All Topics` (???).
 * It's marked as being the default (like how `General` is the default topic) and it's marked as having access to all topics.
 * Every agent always belongs to a team (defaults to the default team).
 * If you delete a team its agents are re-assigned to the default team.
 * If any agent accepts an invitation and the team has been deleted  they are added to the default team.

### CODE REVIEW

**Comment by norkans7** [comment]
I think the default team can always be present in a workspace but the admin would configure the access it has 
`No topic` access , General(as it is default topic) access only, or even `All topics` access.

So the current `All topic` team can be useful too to allow managing agents that will need all topics acces but to me it should no be the default one

**Comment by rowanseymour** [comment]
I don't love that.. thus far we've modeled "system" things as things you can't edit. You can't edit the General topic or the Open Tickets group etc.

**Comment by norkans7** [comment]
I guess then default team could only access default topic
So we have 2 system teams, `default` and `all topics` both not editable

I think default being access to all topics seems not desirable for some users

**Comment by norkans7** [comment]
For the case of an old invite to a deleted team or deleting a team giving access to all topics does not seem right

**Comment by rowanseymour** [comment]
I think the average user isn't going to be gating ticket access by topic and managing teams.. which really only exist for CasePro migration. But they might want to use topics to track what sort of tickets they are handling. By default they're going to want agents to see all topics and not worry about adding topics to teams when they create new topics.

**Review by norkans7 — APPROVED** [review]

**Comment by rowanseymour** [comment]
> For the case of an old invite to a deleted team or deleting a team giving access to all topics does not seem right

This is valid concern.. we can warn when they delete the team.. or we could even cancel the invitations.

**Comment by norkans7** [comment]
This will work for the current use case, but various admins will want to use tickets the other way too, I guess we can adjust that later, probably someone will ask about that

**Comment by rowanseymour** [comment]
If we warn users I guess that's enough because they can go delete the invitations themselves.

**Comment by rowanseymour** [comment]
We can also change all of this in the next few weeks or so because teams are still totally invisible to users - I just want to get the idea of a default team established so we can say all agents belong to a team.

**Pull request merged**
