### PR TITLE
Increase URL max length to 2048

### PR DESCRIPTION
**Pull request by rowanseymour**
https://sentry.io/nyaruka/rapidpro/issues/440622003/

### CODE REVIEW

**Comment by nicpottier** [comment]
Why 1024? Seems 4096 or either 8192 might be more reasonable.

**Comment by rowanseymour** [comment]
I thought people generally tried to keep URLs under < 2000 characters still? It's an arbitrary number but seem like we shouldn't allow 8192 char blobs unless users really need that.

**Comment by nicpottier** [comment]
Try, sure, but why put a limit we know could be higher? Doesn't cost us anything to be inclusive of any URL someone passes us.

**Comment by rowanseymour** [comment]
Well there's a cost even if its small... we have to store these and parse them as expressions and ensure the UI can handle them... are you saying you want no limit at all?

**Comment by norkans7** [comment]
Can a URL shortener help here especially for the message length, I think a long link will be broken if sent in multiple parts

**Comment by rowanseymour** [comment]
These are URLs in attachments not in the message body - no idea what limits different channel types enforce for these

**Comment by nicpottier** [comment]
Looks like 2048 should be plenty and then you don't have to change this again in the future:
  https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Pull request merged**
