### PR TITLE
🔢 Fix boundary aliases duplicates creation

### PR DESCRIPTION
**Pull request by norkans7**
Not clear why the are even duplicated on the form but as first step prevent the duplicates to be inserted in the DB

### CODE REVIEW

**Comment by nicpottier** [comment]
So is the form still showing up with dupes? Wonder if this is an angular issue where after each save we are refetching or re-adding existing aliases to those that already exist?

**Comment by norkans7** [comment]
Right it is something on the the angular side even the validation it is supposed to make is not happening

**Comment by nicpottier** [comment]
I guess my question is with this fix do the aliases still multiply in the UI when you are editing them? Or does this address that?

**Comment by norkans7** [comment]
I think it is still possible, I can't reproduce that locally so that is the reason I made this fix that will save only unique aliases and on reload they will again be unique or we'll better understand where the issue is

**Pull request merged**
