### PR TITLE
Make unique IDs for formax section

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
This generate unique IDs for the posterizer forms and the links that trigger them however I still see many

**Comment by ericnewcomer** [comment]
I thought these shared a single posterizer, I'm not sure why this is necessary. Can you help me understand what's happening here?

**Comment by norkans7** [comment]
The posterizer has a CSRF token field that is the reason they should be different for each form
I am not sure yet why we have multiple requests though

**Comment by nicpottier** [comment]
Could be wrong I don't think the CSRF token needs to be tied to any particular form.

**Comment by norkans7** [comment]
I guess that is because the formax loads each form as a separate request 
I have that assumption from the other time I found having {{block.super}}; which add a new posterizer form, was fixing the issues like the SMTP config updates

**Comment by norkans7** [comment]
Found the proper way to make sure we make one request. Added in https://github.com/nyaruka/rapidpro/pull/2610

**Pull request closed without merging**
