### PR TITLE
API v2 tweaks

### PR DESCRIPTION
**Pull request by rowanseymour**
* Limit ways of filtering messages
 * Return channel with name for consistency

### CODE REVIEW

**Comment by rowanseymour** [comment]
@nicpottier what do you think about restricting use of `contact` with other params for messages and runs?

**Comment by rowanseymour** [comment]
Also I'm not sure now raising a `ValidationError` from `get_queryset` is the correct way to return an error response from a list request, since it renders as a JSON list. Have asked on DRF mailing list what the best practice there is.

**Comment by nicpottier** [comment]
It seems like contact based filtering should be safe since the total # of results will always be small, but maybe looking at some test queries would make that completely clear.

**Comment by nicpottier** [comment]
Yarp!

**Pull request merged**
