### PR TITLE
Wa admin manage

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
I added a `Whatsapp details` view that show the current values set on on WA and that is linked on the gear links from the channel page

RapidPro - Visually build nationally scalable mobile applications 2021-01-20 12-20-01

The details page page show the values and gives options to update each on the gear links

RapidPro - Visually build nationally scalable mobile applications 2021-01-20 12-19-42

We have 3 forms to update About, profile photo and business profile

RapidPro - Visually build nationally scalable mobile applications 2021-01-20 12-20-47

RapidPro - Visually build nationally scalable mobile applications 2021-01-20 12-21-01

RapidPro - Visually build nationally scalable mobile applications 2021-01-20 12-21-16

**Comment by rowanseymour** [comment]
What's the reason for having 3 separate forms? Seems like it would be more natural to be able to update everything from the same form, no?

**Comment by norkans7** [comment]
I think most users check Facebook docs first.
I think mixing them will complicate managing properly and assure the user that changes were applied.

**Comment by rowanseymour** [comment]
Am not following what you mean about checking Facebook docs.. it's not a bit odd to have a single field form for the about field, and separate single field form for the logo..?

**Comment by norkans7** [comment]
By Facebook docs I mean https://developers.facebook.com/docs/whatsapp/api/settings

Do you suggest we show one form and make 3 requests?
How could we manage error to one of them? we resubmit to all of them?

**Comment by rowanseymour** [comment]
Yeah.. but maybe let's get a third opinion @nicpottier @ericnewcomer

**Comment by nicpottier** [comment]
Nice, this will be great to have. To me it feels like maybe these should be dialogs since they are such small forms? Kind of like the editing of a contact field or a channel attribute. @ericnewcomer may have an opinion here on what the "RapidPro" way of doing these kinds of edits is.

**Comment by ericnewcomer** [comment]
@nicpottier took the words out of my mouth. These should be modals either triggered inside the detail page or from the menu as appropriate.

**Comment by norkans7** [comment]
RapidPro - Visually build nationally scalable mobile applications 2021-01-22 14-24-31
RapidPro - Visually build nationally scalable mobile applications 2021-01-22 14-24-18
RapidPro - Visually build nationally scalable mobile applications 2021-01-22 14-24-08

any better option for photo chooser?

**Comment by rowanseymour** [comment]
* Styling for choose photo control should match other upload controls like for import (incidently this is something that seems to be crying out to be a component)
 * I'm still not sure why the about text and photo need to be separate forms/modals.. but I'll defer to what other think.

**Comment by norkans7** [comment]
The other import page are not using modals, for sure a component would the right approach

I tried to use one form with all the fields 
RapidPro - Visually build nationally scalable mobile applications 2021-01-22 17-03-12
I guess we can do that in one form but we get a scrollbar on the modal

**Comment by rowanseymour** [comment]
Yeah I get not combining them all into one modal but the about field and logo would definitely fit on one modal

**Pull request closed without merging**
