### PR TITLE
Allow remove invites

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
manage accounts - nyaruka eric 2017-10-24 17-44-30

**Comment by nicpottier** [comment]
I think we don't show the `Cancel` label in the UI, would be a tad cleaner and the meaning is still clear there. @ericnewcomer

**Comment by ericnewcomer** [comment]
+1 to removing the Cancel label

**Comment by norkans7** [comment]
What about the Invites title?

**Comment by nicpottier** [comment]
I think the invites title is ok, just the cancel one can go.

**Pull request merged**
