### PR TITLE
🔀Add org lock for users to deal with simultaneous updates of org users

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
So we think there were two admins changing users at the same time?

**Comment by norkans7** [comment]
I think users are joining while an admin is inviting other accounts

**Comment by nicpottier** [comment]
Ya, so I don't think locks are really going to solve this. The problem here is basically that we are trying to compare DB state from the form state, even though the form state could be stale and not representing the current world.

Seem fundamentally the problem is that our form should be submitting CHANGES, not the current state. IE, if someone deletes a user, then great, that should be part of the submission but we shouldn't be messing with all the other users. Same with deletion, changing roles etc..

Having a lock won't prevent us from messing things up, as it is now, if I have a window open on that page, then you go add some users, as soon as I save I will overwrite your changes even though we will both have locks.

So I think the real fix is to modify this page and form to be submitting what has changed as opposed to current state.

**Comment by norkans7** [comment]
When we load the form we populate the users we added to the form https://github.com/nyaruka/rapidpro/pull/2356/files#diff-355c85f1d8760973a818313d872fe281L1381

Now when we post I think we should only consider those that were loaded on the form and ignore new users added to the org.

Unfortunately I am not sure how to add test for that since the post in the test was loading he form again

we need the request for the manage_account view to load the form then the other use join then the form is submitted

**Comment by nicpottier** [comment]
This will help for sure, I think there's still potential for races but should be greatly reduced with this.

**Pull request merged**
