### PR TITLE
Add surveyor role, can't do anything on the website

### PR DESCRIPTION
**Pull request by ericnewcomer**
* New user role that can be invited to an org.
* Doesn't have any website privileges other than logging in
* Can be used with the Android client

### CODE REVIEW

**Comment by nicpottier** [comment]
What happens when a surveyor logs in?

**Comment by ericnewcomer** [comment]
It just gives them a login screen again cause they have no website permissions

**Comment by nicpottier** [comment]
Since I think our mechanism for adding new rules involves sending them an email with a link to join the org, create an account etc.. we should probably have a landing page after they actually do log in and become a surveyor.

I'm thinking what makes the most sense there is something pointing them to the Play store to go download the app.. otherwise that whole flow is going to be mega confusing for the surveyors.

**Comment by ericnewcomer** [comment]
Sure, don't disagree. Would you put this as more or less important than survey flow type editor for monday?

**Comment by ericnewcomer** [comment]
I've added a task to track that. Shall we merge? Any other concerns?

**Comment by nicpottier** [comment]
Merge away.

**Pull request merged**
