### PR TITLE
Allow admins to remove themselves from orgs

### PR DESCRIPTION
**Pull request by nicpottier**
We weren't allowing admins from removing themselves from orgs if there was more than one admin on it. This fixes that.

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Should we let the last admin on an org leave?

**Comment by nicpottier** [comment]
We could I suppose, that's another PR though. :)

**Comment by ericnewcomer** [comment]
Oh, I didn't see in here where it was being prevented.. was just curious about orphaned orgs.

**Comment by nicpottier** [comment]
It is (and has been) prevented on the UI side... which isn't ideal, but seems to have worked so far.

**Comment by ericnewcomer** [comment]
Ah. OK, disregard then :)

**Pull request merged**
