### PR TITLE
use poetry 1.4.2 for now

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by rowanseymour** [comment]
@norkans7 what's the issue here?

**Comment by norkans7** [comment]
poetry 1.5.0 not able to `./manage.py`

**Comment by norkans7** [comment]
Not clear to me exactly how that works but that is from https://github.com/python-poetry/poetry/pull/7606

https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md

**Comment by norkans7** [comment]
replaced by #4604

**Pull request closed without merging**
