### PR TITLE
More new styles

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
Flow Start Log 2020-08-03 16-43-56

**Comment by norkans7** [comment]
RapidPro - WebHook Event 2020-08-06 23-04-35
Channel Event 2020-08-06 23-04-12
RapidPro - WebHook Events 2020-08-06 17-34-08
Channel Events 2020-08-06 17-33-53

**Comment by nicpottier** [comment]
Any reason "Recent Channel Events" doesn't have the same elapsed treatment as webhook events? Looks like a tad of extra padding at the bottom of the request for the message log event.

Otherwise looks great to me!

**Comment by norkans7** [comment]
Actually the Elapsed column is treaded the same I mistakenly uploaded the wrong screens
Channel Events 2020-08-10 19-05-21
hot

**Pull request merged**
