### PR TITLE
Delete one object at a time to optimize simulation

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
Msg.objects.filter(contact=test_contact).delete() was taking a long time and the request was timing out

**Comment by nicpottier** [comment]
But this doesn't? How did we test it?

**Comment by norkans7** [comment]
I think it is because we had to many objects and we were trying to delete them at once, I saw a count of 132 and tried the query on the shell and using the the loop was faster

**Comment by rowanseymour** [comment]
I'm a bit wary of changing this without a bit more proof that it helps, as it kind runs counter to our usual aim of reducing db calls through batching.

**Comment by rowanseymour** [comment]
We can revisit this if we run into more simulator performance issues, but closing this for now.

**Pull request closed without merging**
