### PR TITLE
fix to show ivr runs on contact flow results page

### PR DESCRIPTION
**Pull request by norkans7**
this allow users to remove ivr runs in the same way as other runs

https://trello.com/c/llcZq2i0/1598-no-way-to-remove-flow-results-for-ivr-runs

please review @ericnewcomer

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Looks like this page isn't localized at all. Should also add calls to trans and blocktrans as appropriate.

**Comment by ericnewcomer** [comment]
Can you add a screenshot?

**Comment by ericnewcomer** [comment]
Thanks Norbert. This is more appropriately captured in the 'IVR as messages' work

**Comment by norkans7** [comment]
Yep

**Comment by norkans7** [comment]
oh except the localization in the templates

**Pull request closed without merging**
