### PR TITLE
Docker compose dev environment

### PR DESCRIPTION
**Pull request by dodobas**

### CODE REVIEW

**Comment by nicpottier** [comment]
This looks neat and useful, my biggest fear with these types of things is that they rot and fall out of sync making them less useful over time. So my bias is one of:

1) automate the testing of this somehow, perhaps our travis builds could be docker based?
2) put this in another repo where the expectations of maintenance are perhaps less 

Any good ideas on doing 1?

**Comment by dodobas** [comment]
yeah, point 1 is possible, I have already done this for another project https://github.com/healthsites/healthsites/blob/fix_deployment/.travis.yml , it is a bit fiddly to get coveralls to pick up coverage report, but not impossible

We could use the same 'workflow' to build an isolated environment and execute tests in that environment, the question is, do we want to make the switch ?

**Comment by nicpottier** [comment]
So I think we'd have to understand better what we are buying ourselves by using docker for dev. Currently none of us do but that isn't to say perhaps there are advantages to be had. Thus far we haven't run into bugs and behaviors on prod that we don't see on dev, and that's despite most of us deving on OS X vs ubuntu deploys.

I might be more excited about this if it exactly reproduced our prod environment in that it ran celery processes and such as well and made that easy to do, but to some extent that is being covered by https://github.com/rapidpro/rapidpro-docker. That's something that I could see being more useful on occasions when there is a threading issue you are tracking down. Having a dev environment in docker which I don't feel is buying us much. (again willing to have my eyes opened here)

On the other hand I think it might be nice to have a /recommended/ dev environment and perhaps this would move us towards that, just not sure how many of us are going to adopt it apart from you. (but perhaps you can convince us next week!)

**Comment by nicpottier** [comment]
On running this on travis I think that'd be interesting, isn't that docker in docker? (how far do the turtles go down!?) What would be the performance impact for our already pretty pocky builds?

**Comment by dodobas** [comment]
yeah, we should have a broader discussion about impact of these changes

**Comment by ericnewcomer** [comment]
+1 to putting this on ice until we can see ur environment in person!

**Comment by dodobas** [comment]
this is not important at the moment, closing

**Pull request closed without merging**
