### PR TITLE
Add button to facilitate selecting all fields on import to be included

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
select-all

**Comment by rowanseymour** [comment]
I think from a UI perspective these buttons should be visually less prominent than the default buttons for doing the import. Maybe make them grey and smaller?

**Comment by norkans7** [comment]
Good point

**Comment by norkans7** [comment]
select-all2

**Comment by norkans7** [comment]
We need to have fields selected by default,... and select2 widget for contact fields

**Pull request closed without merging**
