### PR TITLE
👶 Dummy migrations for all migrations created by actual squashing

### PR DESCRIPTION
**Pull request by rowanseymour**
Have checked that if you apply these migrations, then you can check out https://github.com/nyaruka/rapidpro/pull/2459 and `migrate` will say there are no migrations to apply

### CODE REVIEW

**Comment by nicpottier** [comment]
So I think we just merge this once the tests pass, then upmerge then we are done?

**Comment by rowanseymour** [comment]
@nicpottier yeah I think so. 

I know these PRs aren't so reviewable but you might have noticed in https://github.com/nyaruka/rapidpro/pull/2459 that all the SQL initial stuff goes into a single migration in sql/ (which becomes a real django app even in this PR). That makes it a little less shit work cuz then as the current_*.sql files become the initial SQL state and you don't have to go put all those SQL things back in the apps that first created them.

This differs from previous squashes I've done where I've I created 0002_indexes, 0003_functions, 0004_triggers migrations in each app. That approach would have also required a lot more dummy migrations in this PR.

**Comment by chris-erickson** [comment]
This one safe to deploy out, or should I be cautious about it for now?  Been deploying ~ once per week on Fridays so we don't fall behind and it's been going well.

**Comment by nicpottier** [comment]
Yes, you should ship 5.0.9 (which includes this) and then future deploys when we've done the squashing on 5.1 should go swimmingly.

**Pull request merged**
