### PR TITLE
Fix export styles and broken workspace home links

### PR DESCRIPTION
**Pull request by norkans7**
Fixes https://github.com/rapidpro/rapidpro/issues/1365 and https://github.com/rapidpro/rapidpro/issues/1344

### CODE REVIEW

**Comment by rowanseymour** [comment]
@norkans7 screenshot for the export page fix?

**Comment by norkans7** [comment]
RapidPro - Visually build interactive SMS Applications 2020-10-21 16-02-27

**Review by ericnewcomer — APPROVED** [review]
Padding off slightly on export group titles, but otherwise seems fine. This PR also looks like it's setting the country select to be searchable. I think I'd like to see that as a mixin instead to apply across all channels automatically, but this is fine.

**Comment by norkans7** [comment]
RapidPro - Visually build interactive SMS Applications 2020-10-23 20-25-35

**Comment by rowanseymour** [comment]
not the fault of this PR but looking at that screenshot, don't we always use a checkbox component? @ericnewcomer

**Pull request merged**
