### PR TITLE
escape action logs text when we are create them

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
So my point was that we don't need to add a ```safe``` attribute to the ActionLog if we just make sure we never put anything in it that isn't safe. (IE, we escape user content as we put it in)

Seems this is still using a ```safe``` attribute.

**Comment by norkans7** [comment]
safe is passed to the classmethod so I do not process the text in many places

**Comment by nicpottier** [comment]
Ah ok, great!

Looks like we've kind of standardized around the help method being called ```create``` ie, not ```create_action_log```, can you switch that and then we are all set!

**Comment by norkans7** [comment]
Sure, I update that

**Pull request merged**
