### PR TITLE
Optimizations for the runs endpoint

### PR DESCRIPTION
**Pull request by rowanseymour**
* Prefetch step messages to avoid repeat fetches
* Use subqueries to filter by flow and contact where possible to avoid large joins

### CODE REVIEW

**Comment by rowanseymour** [comment]
I experimented with bringing the groups/group_uuids filters up into the subquery for contacts but it proved slower than joining on the tables.

group #1 (size: 57785)
subquery: 1m 32s
join: 46s

group #2 (size: 248876)
subquery: 6m 52s
join: 1m 17s

**Comment by nicpottier** [comment]
What are those timings on? 46 seconds is still on the bleeding edge..

**Comment by rowanseymour** [comment]
When fetching runs by contact group. In that case we need to join on contacts / contact_group etc. For example grabbing first page of runs for everyone in the UReporters group:

```sql
SELECT "flows_flowrun".*
FROM "flows_flowrun"
      INNER JOIN "contacts_contact" ON ( "flows_flowrun"."contact_id" = "contacts_contact"."id" )
      INNER JOIN "contacts_contactgroup_contacts" ON ( "contacts_contact"."id" = "contacts_contactgroup_contacts"."contact_id" )
      INNER JOIN "contacts_contactgroup" ON ( "contacts_contactgroup_contacts"."contactgroup_id" = "contacts_contactgroup"."id" )
WHERE (
      NOT ("flows_flowrun"."contact_id" IN (SELECT U0."id" FROM "contacts_contact" U0 WHERE (U0."is_test" = true AND U0."org_id" = 2)))
      AND "flows_flowrun"."flow_id" IN (
            SELECT U0."id" FROM "flows_flow" U0 WHERE (U0."org_id" = 2 AND U0."is_active" = true)
      )
      AND "contacts_contactgroup"."group_type" = 'U' AND "contacts_contactgroup"."uuid" IN ('55e29b7d-a541-45ee-bcde-a4e82afff940')
)
ORDER BY "flows_flowrun"."id" DESC LIMIT 250;
```

I'd imagine that filtering runs by contact group might be high on the list of things to prune for an API v3.

**Comment by nicpottier** [comment]
Hrmm.. ya, probably wouldn't be super missed honestly.

So how long does paging a flow on Nigeria take now?

**Comment by rowanseymour** [comment]
Querying for all runs:

Counting all: ~20s (first page only)
Fetching page: ~1s

**Comment by nicpottier** [comment]
Sorry to pester, but what were they before?

**Comment by rowanseymour** [comment]
Counting all: ~40s
Fetching page of runs: ~200s
Message fetching x 250: ~8s

**Pull request merged**
