### PR TITLE
📶 Fix starting simulation for new orgs

### PR DESCRIPTION
**Pull request by norkans7**
Fix 

https://sentry.io/nyaruka/textit/issues/876300089/

https://sentry.io/nyaruka/textit-mailroom/issues/876300075/

the flow was failing to load

### CODE REVIEW

**Comment by nicpottier** [comment]
How does this happen in the UI? Its not the common path right?

**Comment by norkans7** [comment]
simulator just fails and hangs

**Comment by nicpottier** [comment]
But in what case? All simulation isn't broken is it?

**Comment by norkans7** [comment]
It is probably for new orgs only that it fails where mailroom needs to load Org assets

**Comment by norkans7** [comment]
This will set the flow for the https://github.com/nyaruka/rapidpro/blob/master/temba/flows/views.py#L1475

then https://github.com/nyaruka/mailroom/blob/master/web/simulation/simulation.go#L81 will load the flows correctly

**Comment by nicpottier** [comment]
But what's different about new orgs? Wouldn't this fail for all of them?

**Comment by nicpottier** [comment]
Looking at timestamps, it looks to me the root error is this one:
  https://sentry.io/nyaruka/textit-mailroom/issues/876300075/?query=is%3Aunresolved

New orgs don't have the labels created and mapped properly for the demo flows.

**Comment by norkans7** [comment]
The issue is with the flow_imports not remapping the labels

**Pull request closed without merging**
