### PR TITLE
Add channel type in channel expression context

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
Is this in response to a ticket? Can you link it?

**Comment by norkans7** [comment]
https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/155964/conversations/18282740791

**Comment by rowanseymour** [comment]
@norkans7 @nicpottier couldn't they do the same thing with URN scheme? Just wondering if channel codes are more of an internal detail than something we want people building logic around.

**Comment by norkans7** [comment]
We expose @contact.[scheme] as the scheme URN and we do not know how to check the channel being interacted with 
And on anon org all we can test is if the value is not empty

**Comment by nicpottier** [comment]
I thought scheme was indeed the way we do this.

**Comment by rowanseymour** [comment]
In new engine even an anon-org can do `@contact.urns.0.scheme` (only path is redacted).. wonder if we can't make something similar work in old world. It's not the end of the world if we have to expose channel types but things like `TW`, `NX` feel more like Courier implementation details than part of a flow spec.

**Comment by norkans7** [comment]
Replaced by #2094

**Pull request closed without merging**
