### PR TITLE
Make sure the FlowPathRecentMessage display the value used in the rul…

### PR DESCRIPTION
**Pull request by norkans7**
…eset to split

### CODE REVIEW

**Comment by norkans7** [comment]
On this we need to discuss why only wait ruleset are displayed on the results page and not the other rulesets

**Comment by rowanseymour** [comment]
I'm not quite understanding this PR. Are we trying to show recent messages or recent values? Did the switch to `FlowPathRecentMessage` change the existing behaviour?

**Comment by norkans7** [comment]
When a flow has a split by contact field, users expect the "recent messages" popup to show the value used to decide the split however currently we show the last incoming message. This PR will adjust to show the value used by the ruleset to decide the next path to take

**Comment by ycleptkellan** [comment]
👍 excited about this one

**Comment by nicpottier** [comment]
I agree this could be useful but wondering how confusing this might be for users as well. We've always showed last message here, so this would be new behavior wouldn't it? Also need to ponder how we would make this work in GoFlow though I think that'd likely be fairly straightforward. @ericnewcomer?

**Comment by rowanseymour** [comment]
Am also concerned that this gets confusing if users no longer know if they are looking at a message, a part of a message, a part of a contact field etc. Maybe what's needed here is linking to the contact along with the message, so users can easily see which contacts took a path - they can always click on the contact then to see their fields if that's what is being used by a particular ruleset.

**Comment by norkans7** [comment]
When I saw this, the user had two ruleset stacked, I think showing the value used for the decision is what I would expect on the pop up.  And those who really want to see the incoming message they can have two ruleset like that

**Comment by ericnewcomer** [comment]
Honestly, I would really prefer to not show this new information in the exact same way as other, this would be confusing. If we want to surface this information, we need a different treatment altogether. In these cases, since today the output is the same, I'd be more amenable to suppressing that and coming up with a better interface for the debugging of how things were evaluated.

If we really wanted to use the same rollovers, perhaps there's a better way to display that so things are less confusing.. ie, a header for Recent Messages, Expression Results, etc. inside that rollover.

**Comment by rowanseymour** [comment]
There are two different things we're trying to do here:

 1. Show users _who_ is taking a particular path segment
 2. Help users see _why_ those contacts are taking that path

IMO just displaying value won't always suffice for no. 2 because expressions can contain all sorts of weirdness - but putting contact on the rollover is straightforward (we're storing a reference to the run) - and gives users a way of figuring out the answer to no. 2

**Comment by nicpottier** [comment]
To me it feels like 2) is the more useful thing here, it certainly is where people seem to derive the most value presently and also why we added the feature in the first place.

I do think it might be slightly confusing but still worth it to put the operand value on the exits of rulesets. As you said, expressions can be nuts and what better way to help people debug what is happening than having that operand displayed near the exit where it was routed?

The only place this would really be different is for users who use advanced expressions, the current behavior would be the same for those just doing splits on messages, as @step.value is already the operand.

I certainly would have found this useful when designing some of the more advanced flows doing splits on webhook results.

**Comment by rowanseymour** [comment]
2) might be more useful but 1) is simpler to understand - i.e. we don't have to explain to the user "this is a message you're looking at". So I think we need something like @ericnewcomer's suggestion of different headers within that rollover.

Also definitely want a solution here that doesn't involve rebuilding the context to figure out what the operand value was. Rebuilding the context is expensive.

If there's not an easy way to do with the existing engine, that then I'd lean toward punting on this until we move to the new engine.

**Comment by rowanseymour** [comment]
Closing this for now - we'll revisit this problem when we're running on the new engine and editor.

**Pull request closed without merging**
