### PR TITLE
Allow use of shared shortcodes on AfricasTalking

### PR DESCRIPTION
**Pull request by nicpottier**
Lets users use one of the Africa's Talking shared shortcodes.. this basically is just a flag set when connecting that then changes our send format a bit.

### CODE REVIEW

**Comment by nicpottier** [comment]
plz review

**Comment by ericnewcomer** [comment]
So for shared shortcodes, we don't send the from? What does it end up being? Do they have longcodes for each person sharing at that point?

**Comment by nicpottier** [comment]
This is an API weirdness on their part, as they've explained it the FROM will still be the shortcode, but they don't allow you to specify it when sending.

**Comment by ericnewcomer** [comment]
Huh, super weird. Merge away.

**Comment by norkans7** [comment]
I see they say it is not required they have a default one

**Comment by norkans7** [comment]
http://docs.africastalking.com/sms/sending/python

I think we can still set it instead of having the default set

**Comment by nicpottier** [comment]
Ya, this PR came from a private email convo I had with one of their engineers as one of Thomas's orgs is struggling with it.

**Pull request merged**
