### PR TITLE
Django 1.10 / Migration Purge

### PR DESCRIPTION
**Pull request by nicpottier**

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Hooray. What's the smartmin change bring?

**Comment by nicpottier** [comment]
That's changing import tasks to use their own DB status instead of celery
tombstones

**Comment by nicpottier** [comment]
Guessing 1.10 must build its migration dependency subtly different than 1.9, so it is dying due to that. Will try comparing ordering of all our migrations being applied on 1.9 vs 1.10 tomorrow

**Comment by nicpottier** [comment]
Replaced with real django-110 branch.

**Pull request closed without merging**
