### PR TITLE
Improve styles for recipients

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
Addresses https://github.com/rapidpro/rapidpro/issues/1387#issuecomment-736598472

**Comment by norkans7** [comment]
BEFORE, flow start list broken and can not scroll
Flow Start Log 2020-12-04 17-10-21
Doctor Reminders (Archived) 2020-12-04 17-09-59


AFTER 

Flow Start Log 2020-12-04 17-10-59
Doctor Reminders (Archived) 2020-12-04 17-10-48

**Comment by rowanseymour** [comment]
Captura de Pantalla 2020-12-04 a la(s) 10 44 38

I think this would look better 1) left-aligned and 2) with more line spacing

**Comment by norkans7** [comment]
Flow Start Log 2020-12-04 18-02-53

The right alignment was from the trigger list page however I think that is fine to align the recipients there on the left too

**Comment by ericnewcomer** [comment]
Wait, this is inner-scrolling recipient lists? Why not just let the page stretch in this case?

**Comment by norkans7** [comment]
@ericnewcomer the inner scrolling is now removed

**Review by rowanseymour — APPROVED** [review]

**Pull request merged**
