### PR TITLE
Start flow in background for event batch firing

### PR DESCRIPTION
**Pull request by norkans7**
This will prevent https://sentry.io/nyaruka/textit/issues/318526310/events/9779679041/

### CODE REVIEW

**Comment by nicpottier** [comment]
I wonder if we should actually just be doing these one at a time instead, which seems it would balance our handling queue a bit better. (IE, give resources to interactive flows over campaign flows)

We lose the efficiency that comes from batching a set of flows together in that case though.

**Comment by rowanseymour** [comment]
FYI we only recently changed these to use batches https://github.com/nyaruka/rapidpro/commit/cbe7f8fd95d465a7a69a5cb78d418c7dee444a02#diff-8a47789b2c9de7beb2c22be6a4d78f2e

**Comment by norkans7** [comment]
I think most of the times the campaigns fire for just a single contact so yes it seems right to just fire one by one or we change this to check and if we have one contact we just start the flow other wise we make a FlowStart object as we do for triggers

**Comment by rowanseymour** [comment]
@norkans7 we just chatted about this and your solution here seems right

**Comment by norkans7** [comment]
That means we are fine having FlowStart objects to just one contact?

**Comment by nicpottier** [comment]
Ya, agree we should treat single contact case differently.

**Pull request merged**
