### PR TITLE
Support exporting a system label of messages

### PR DESCRIPTION
**Pull request by rowanseymour**
Requires merging #1201 first to make diff readable

screen shot 2017-04-06 at 15 39 34

screen shot 2017-04-06 at 15 40 02

### CODE REVIEW

**Comment by nicpottier** [comment]
The UI czar (@ericnewcomer) may disagree but don't we tend to use select2 drop downs over single selects like this?

**Comment by ericnewcomer** [comment]
Agree with @nicpottier that we've not used radios to date, ought to follow the same select2 strategy here

**Comment by rowanseymour** [comment]
That's fine - just wasn't sure if dropdown was appropriate for something which is a binary choice. I tried checkbox initially but it doesn't lend itself to providing an explanation of both options.

**Comment by rowanseymour** [comment]
@nicpottier @ericnewcomer updated to use dropdown, e.g.

screen shot 2017-04-10 at 16 21 11

**Pull request merged**
