### PR TITLE
🕯️ Don't blow up if someone calls contact_action endpoint with zero contacts

### PR DESCRIPTION
**Pull request by rowanseymour**
Fixes https://sentry.io/organizations/nyaruka/issues/1632972355/?project=20737&referrer=alert_email

### CODE REVIEW

**Comment by nicpottier** [comment]
Shouldn't this be a 400? I mean, we don't want to encourage people being so lazy that they can't even figure it if they have a contact to call to take an action do we?

**Comment by rowanseymour** [comment]
I've gone back and forth on that... I'm fine with it being an error - just need to make it always an error. Right now it's only an error for the interrupt case.

**Comment by nicpottier** [comment]
I think calling us with no contact is a programming error, so I'd rather see it be a 400 than a no-op. Same argument as say a Django update failing if it selects no rows.

**Comment by nicpottier** [comment]
Oops, wrong button.

**Comment by rowanseymour** [comment]
So following on from the Django example, are we then saying it's an error if it makes zero real changes? For example passing in a blocked contact to be blocked?

**Comment by rowanseymour** [comment]
My inclination is no.. it's just an error to pass in an empty contact array.

**Comment by nicpottier** [comment]
That one is a bit of a higher bar for the client to know the current status of the contact, so no, I would say that isn't anything. Does Django consider that an error? I think only if your select before the update is on no rows, not that nothing changes. (could be wrong though)

**Comment by rowanseymour** [comment]
Ah you're right about Django

**Comment by rowanseymour** [comment]
Updated to error if contacts is empty

**Pull request merged**
