### PR TITLE
🏎️ Tweak contact indexes

### PR DESCRIPTION
**Pull request by rowanseymour**
```
BEGIN;
--
-- Create index contacts_contact_org_modified on field(s) org, -modified_on, -id of model contact
--
CREATE INDEX "contacts_contact_org_modified" ON "contacts_contact" ("org_id", "modified_on"DESC, "id"DESC);
--
-- Raw SQL operation
--

DROP INDEX contacts_contact_org_modified_id_active;
DROP INDEX contacts_contact_name;
;
COMMIT;
```

### CODE REVIEW

**Review by nicpottier — APPROVED** [review]
annoying that django doesn't use concurrently...

**Review by nicpottier — CHANGES_REQUESTED** [review]
Now that I'm thinking about it, doesn't U-Report iterate across all active contacts? If that's the case, then paging to contact 1,000,000 would require a constraint check for a million rows when getting to that page right? So maybe we do still need the active one.

**Comment by rowanseymour** [comment]
U-Report and CasePro both sync contacts so if someone changes a million contacts, they fetch a million contacts (4000 pages?)... but not quite following what you mean by a constraint check?

**Comment by nicpottier** [comment]
If you are on page 3999, then the DB is going to have to load the row for all the previous 999,999 rows to check that `is_active` is true if it isn't part of the index.

**Comment by nicpottier** [comment]
(I think so at least based on my understanding of how the paging works, maybe we need to look at that query to double chekc)

**Comment by rowanseymour** [comment]
Yeah I think you're right - it would scan thru that entire index but have to filter on is_active=true... have put that index back

**Comment by rowanseymour** [comment]
hmm well now that we're not trying to share this index with the API seems it should be just ` (org_id, modified_on DESC)` and  `(org_id, modified_on DESC, id DESC)`.. it's only going to be used for oldest modified on lookup..

**Pull request merged**
