### PR TITLE
Long message wrapping

### PR DESCRIPTION
**Pull request by rowanseymour**
Addresses https://github.com/rapidpro/rapidpro/issues/308 which affects inbox views and contact history view.

Before:
screen shot 2016-10-04 at 12 07 46

screen shot 2016-10-04 at 13 07 43

After:
screen shot 2016-10-04 at 12 06 33

screen shot 2016-10-04 at 12 56 07

Difficulty is that the CSS wrapping properties only seem to take affect if the container has a fixed size - so I've added max-width settings. That becomes noticeable on history view if page is really wide:

screen shot 2016-10-04 at 12 56 22

### CODE REVIEW

**Comment by nicpottier** [comment]
Can max width just be arbitrarily large so there's no difference even on wide screens?

**Comment by rowanseymour** [comment]
@nicpottier no it seems the word based wrapping only starts when you hit/exceed the max-width - if you wanna experiment: https://jsfiddle.net/203a50xs/

**Comment by nicpottier** [comment]
Ah in that case seems we need two different values based on what grid size we are in no? (we snap to two different grid sizes)

**Comment by rowanseymour** [comment]
The difficulty is that the table cell is % width of a responsive table, so even with a media query based on screen size - we can't really say what the table cell width should be.

However it appears that setting `max-width: 0` does the trick even tho it's a hack. You can play with that at https://jsfiddle.net/203a50xs/4/ and I've tested it on IE9+10/Chrome/Opera/Firefox

Go idea from http://stackoverflow.com/a/26293398 and http://stackoverflow.com/a/11877033

**Comment by rowanseymour** [comment]
@nicpottier this is updated with the thing that we shouldn't call a hack but essentially is a hack

**Comment by nicpottier** [comment]
Totally not hack! It's HTML the whole thing is a hack!

**Pull request merged**
