### PR TITLE
Feature/template translation country

### PR DESCRIPTION
**Pull request by koallann**
Issue: https://github.com/rapidpro/rapidpro/issues/1206

So do we need to update the `goflow` by referencing that country field?

### CODE REVIEW

**Comment by koallann** [comment]
Yep, due to the code_check's runs, I thought that Travis CI must be passing at least. Okay, thanks.

**Comment by rowanseymour** [comment]
@koallann if `code_check.py` is making changes it shouldn't be, please check you have the right versions of things like `black` as set in `pip-freeze.txt` (easiest to just rebuild your virtualenv)

**Comment by rowanseymour** [comment]
PR for goflow changes at https://github.com/nyaruka/goflow/pull/920

**Comment by rowanseymour** [comment]
@koallann the goflow/mailroom side of this is done - mailroom just needs a small tweak to load country from the db when that field is added to the db

**Comment by koallann** [comment]
PR for Courier: https://github.com/nyaruka/courier/pull/308q

**Comment by nicpottier** [comment]
Going to merge this and fix coverage.

**Comment by koallann** [comment]
@rowanseymour can [that Mailroom's line](https://github.com/nyaruka/mailroom/blob/6148ee3070de89868f329fc950b04746b14fe29e/models/templates.go#L95) be enabled now?

**Comment by nicpottier** [comment]
I'm taking care of it.

**Pull request merged**
