### PR TITLE
⚠️ Show if flow has issues on flow list page

### PR DESCRIPTION
**Pull request by rowanseymour**
Adds https://github.com/rapidpro/rapidpro/issues/1163

 * Make `Flow.has_issues` non-null
 * Cleanup unused localized strings on `Flow` model
 
Captura de Pantalla 2021-05-12 a la(s) 13 14 56

### CODE REVIEW

**Review by norkans7 — APPROVED** [review]

**Comment by nicpottier** [comment]
Does clicking on the icon do anything? A bit worried about this causing concerns for users without having a good explanation right off the bat. (do we have hovers at least?) Also wonder about the treatment with the run counts. Should we always right indent run counts in so there is room for the icon?

**Comment by rowanseymour** [comment]
Clicking just opens the flow and then you see the issues tab. There's a tooltip text that says "Has issues"

**Comment by rowanseymour** [comment]
You mean always have the icon in its own column to the left of the run counts?

**Comment by nicpottier** [comment]
I was originally thinking to the right of the run counts, but maybe that would be weird. I guess it is probably ok and easy enough to tweak if it comes down to it later.

**Comment by rowanseymour** [comment]
I think we also might want to tweak the icon color but there seems to be wider problem of lots of these icons now being very black.. so figured we can address that separately.

**Pull request merged**
