### PR TITLE
Replace response_to index with partial only used when present

### PR DESCRIPTION
**Pull request by nicpottier**

### CODE REVIEW

**Comment by ericnewcomer** [comment]
This won't actually drop the index will it? Are you sure we need the partial one at all?

**Comment by nicpottier** [comment]
It will drop the old one, ran the migration locally and checked.
The partial might be nice if we ever do reverse lookups but perhaps it makes sense to cross that bridge when we get there. Of the ~200M rows we have, 30M have response_to set.

**Comment by ericnewcomer** [comment]
Ya, I say don't even create the partial one. I'd very much rather build them later as we see a need for them.

**Comment by ericnewcomer** [comment]
hit it!

**Pull request merged**
