### PR TITLE
Fixed params to /runs API endpoint

### PR DESCRIPTION
**Pull request by rowanseymour**

### CODE REVIEW

**Comment by rowanseymour** [comment]
Fixes https://app.getsentry.com/nyaruka/textit/group/52245453 and broken `after` param

**Comment by norkans7** [comment]
why change getlist to get?

**Comment by rowanseymour** [comment]
`getlist('foo')` expects multiple params to be provided like `foo=1,foo=2` whereas in our docs we tell users to send multiple params like `foo=1,2`

**Comment by norkans7** [comment]
right, I see

**Pull request merged**
