### PR TITLE
Valid contact fields from api

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
Yep, though can you add a test for the API that trying to create a reserved field fails?

**Comment by norkans7** [comment]
there is one at https://github.com/nyaruka/rapidpro/blob/valid-contact-fields-from-api/temba/contacts/tests.py#L1573

**Comment by nicpottier** [comment]
That's testing the method, not the API call.

**Comment by norkans7** [comment]
ok I add that too

**Comment by nicpottier** [comment]
Perfect!

**Pull request merged**
