### PR TITLE
Flow sessions part 1

### PR DESCRIPTION
**Pull request by rowanseymour**
`FlowRun.session` and `Msg.session` are currently optional channel sessions, and in the new_engine branch we've been trying to model a session with goflow as a type of channel session. 

This flips things around so every run and message will have a `FlowSession` (GOFLOW (?), IVR, USSD). IVR and USSD sessions will contain a `ChannelSession` with all the channel specific stuff.

For now this PR just adds the `FlowSession` model and ensures that new `ChannelSession` instances have a container `FlowSession`. Next steps would be..

 1. A migration to add  `FlowSession` containers for old `ChannelSession` instances 
 2. Change `FlowRun.session` and `Msg.session` to be the flow session

### CODE REVIEW

**Comment by ericnewcomer** [comment]
The session type here still kinda bugs me. To me, IVR or USSD FlowSession types will likely ultimately run over the go engine.. Is maybe the third type just Messaging? Seems whether it routes over the go engine should be captured elsewhere. But even then, is the type here actually useful? Shouldn't that just be captured by the ChannelSession (or connection or whatever we call it) if it has some relevant data there?

**Comment by rowanseymour** [comment]
I think you're right - at some point everything will have a FlowSession. Some will have an associated thing with some channel state (connection ?), and at the top level the session (and goflow itself) won't be concerned what the flow type is. The question is how we get from here to there.

**Comment by rowanseymour** [comment]
@nicpottier @ericnewcomer how does this look:

```
channels.ChannelSession:
  external_id
  status
  channel
  contact
  contact_urn
  direction
  started_on
  ended_on
  org
  session_type
  duration
```

Becomes

```
flows.FlowSession:
  org
  contact
  status (active/waiting/errored/completed)
  started_on
  ended_on
  connection (one-to-one)
```

```
channels.Connection:
  connection_type (IVR/USSD)
  channel
  contact_urn
  external_id
  status (in_progress/no_answer... etc)
  direction
  duration
```

**Comment by nicpottier** [comment]
Seems sane to me.. are `Connection` to `Session` always one to one? I seem to remember something about IVR calls starting a new session for subflows or something @ericnewcomer  do you remember?

For some reason I have a bad memory of one to one fields in Django vs just a foreign key but I can't remember why.

**Comment by ericnewcomer** [comment]
I think IVR did create spurious sessions at one point but believe that was a bug that was addressed. Should only be one IVRCall (ChannelSession) per call today.

Would connection duration be as reported from an external service? Otherwise, seems we wouldn't need it since it can be deduced from session start and session end. At any rate I think this makes sense. Only real limitation is if we wanted to support some kind of handoff between modalities, but I think it's best to force a new session in that case.

**Comment by rowanseymour** [comment]
One-to-one means there's a uniqueness constraint on the foreign key, and both `A.b` and `B.a` are single objects - so that seems right if we don't want a connection spanning multiple sessions.

ChannelSession.duration seems to sometimes come from the external service.

**Comment by rowanseymour** [comment]
Latest version of this PR now:

- Adds a barebones `FlowSession` model
- Renames `FlowRun.session` (FK to `ChannelSession`) to `FlowRun.connection`
- Adds `FlowRun.session` (FK to `FlowSession`)
- Ensures that all new instances of `USSDSession` and `IVRCall` are created with a `FlowSession` instance
- Renames instances of `USSDSession` and `IVRCall` from `session` to `connection`

Next step would be:
- Move fields from `ChannelSession` to `FlowSession` that will be common to all flow sessions

Areas for discussion/review:
- Do we have a data migration to create `FlowSession` instances for all old `USSDSession` and `IVRCall` instances, or is `FlowSession` a temporary thing which only really needs to exist whilst its active?
- How to rename `ChannelSession` to `ChannelConnection` without proxy models blowing up (see https://code.djangoproject.com/ticket/23521)

@nullcode can you take a look at the implications for USSD here. I'm a little confused currently as it seems we create new USSDSessions for subflows (i.e. https://github.com/nyaruka/rapidpro/blob/fb86501d68525faf8664d6c9e1c7e6bc59bc33f7/temba/flows/models.py#L1503), but I would have thought a USSD session would span across flows.

**Comment by nullcode** [comment]
@rowanseymour yeah you are right, it should be one session for all, I think that's some left over code, AFAIK ChannelSession.parent doesn't even exist anymore (maybe @ericnewcomer knows more about this).

**Comment by rowanseymour** [comment]
@nullcode yeah so I've logged that here https://github.com/rapidpro/rapidpro/issues/622 and whilst I was poking around in there I noticed you also can't create a USSD flow that starts with an action https://github.com/rapidpro/rapidpro/issues/621. 

FYI the new `FlowSession` model is a temporary thing that will track a contact's session with the goflow engine across different runs. We're renaming ChannelSession stuff to "connection" to avoid confusion, and it will continue to track channel specific stuff.

**Pull request merged**
