### PR TITLE
Django 1.9: Rework channel handlers to not need REQUEST

### PR DESCRIPTION
**Pull request by rowanseymour**
This isn't finished but making PR now so folks can see the approach thus far. 

Made a base class for channel handlers which will provide a GET/POST agnostic way of getting params. Then figured it would be nice if handler classes were a bit more self-contained and provide their own URLs.

### CODE REVIEW

**Comment by nicpottier** [comment]
Seems fine. Making the views know their URL seems a bit anti-Django and I'm not sure that really saves you anything though.

**Comment by rowanseymour** [comment]
Yeah no huge win at this point but I think it makes it easier to 1) see what URL kwargs are configured and 2) move to having channels be self-contained modules.

**Comment by nicpottier** [comment]
2) is a strong argument so full speed ahead!

**Comment by rowanseymour** [comment]
At some point it seems we should move the sending code into the channel handlers, yeah?

**Comment by nicpottier** [comment]
Ya, the ultimate endgame would be one file per new channel type which contains any special view stuff, sending code and handling code. Then dynamically have those loaded..

**Pull request merged**
