### PR TITLE
🐎Easy way to service flows

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
What is this doing exactly?

**Comment by norkans7** [comment]
Some users are on multiple orgs and It is time consuming to support them once you know the flow you go directly to the org with this

**Comment by rowanseymour** [comment]
@norkans7 if I login as one org and then try to view a flow from a different org, I don't see any gear button for that flow... because I don't have edit/delete rights for that flow, right? With this change I get a single option to Service?

**Comment by norkans7** [comment]
Correct @rowanseymour

**Pull request merged**
