### PR TITLE
More styles

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
RapidPro - Visually build interactive SMS Applications 2020-08-12 17-55-51
Results - Pick a Number 2020-08-12 17-55-15
Join WFP Rwanda 2020-08-12 17-54-53
Join WFP Rwanda 2020-08-12 17-54-37
RapidPro - Visually build interactive SMS Applications 2020-08-12 17-54-06

**Comment by norkans7** [comment]
RapidPro - Visually build interactive SMS Applications 2020-08-13 18-13-53

**Comment by ericnewcomer** [comment]
90159579-e4179000-dd90-11ea-874b-02574d42aa45

**Comment by ericnewcomer** [comment]
Screen Shot 2020-08-13 at 9 57 35 AM

**Comment by ericnewcomer** [comment]
Screen Shot 2020-08-13 at 10 03 08 AM

**Comment by johncordeiro** [comment]
hey guys, I've found this issue and I'm looking at how amazing these new styles are! Did you guys think of using a side menu in RapidPro? 

Especially because all the modern web apps are using and it improves the learning process for new users. We've identified that people struggle to find the workspace home for the first time (by clicking in the workspace name on the top right).

**Comment by norkans7** [comment]
@johncordeiro so you mean an additional side menu or just move the entire menu?
 I am wondering if a org home menu on the current menu would be enough for that issue

**Comment by johncordeiro** [comment]
The suggestion would be to replace the side menu instead of the top one, even to change a little bit, as the current menu is there for a while. A new look and feel for RapidPro would be welcome to the users.

**Comment by nicpottier** [comment]
@johncordeiro Looking at the nav is on the roadmap after this style refresh yes.

**Comment by ericnewcomer** [comment]
@johncordeiro yes, reworking the nav is on our longer term list and a left-side nav is reasonably likely (but not set in stone). The work you are seeing here is just a refresh for consistency across the product which intentionally doesn't make any UX changes so as to not disrupt our customers too rapidly.

I've included a mockup from a while back just so you know there is active thought around this happening. But again, this is not part of the current refresh work and something that needs a lot more thought before we make changes that affect how users interact with the product.

AAA7EC47-86C5-4B4F-9D32-264041ED6E91-40391-0000506EA87C3326

**Comment by johncordeiro** [comment]
Thanks for sharing this @ericnewcomer . I would like to know how my team can help with that. I have a React specialist in the team, so we can collaborate together in the component creation. Are you guys still using Slack? I'm so excited about this picture 😊

**Comment by ericnewcomer** [comment]
The rapidpro main interface does not use React and that's not likely to be in the offing. That said, we have started adopting some use of web components: https://github.com/nyaruka/temba-components

I still think the best way to collaborate is right here on github via opening PR drafts for discussion. Utilizing those components to build rich interfaces in RapidPro (reworking some UX pipelines, etc) is perhaps where I could see your team make contributions. We'd definitely want to keep the bar for any new UX work high as we continue to button things up.

Ok, best we stop threadjacking @norkans7's PR now :)

**Comment by norkans7** [comment]
Manage Logins - WFP Rwanda 2020-08-17 14-24-18

**Pull request merged**
