### PR TITLE
Disable modal to close on ESC key

### PR DESCRIPTION
**Pull request by norkans7**
Follow up on https://github.com/nyaruka/rapidpro/pull/562#issuecomment-183108759

- Disable ESC to close modal so ESC will be closing popup if pop up is shown

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Can you explain the purpose for all the resolveObj changes?

**Comment by norkans7** [comment]
I added a method `openModal` on the Flow service

**Comment by norkans7** [comment]
actually I think I can remove $modal in the controllers

**Comment by ericnewcomer** [comment]
Fine with encapsulating the modal creation. However, I would argue that the FlowService is not the right place for that. Perhaps one for utils would be more suitable.

**Comment by norkans7** [comment]
Okay, I'll move that to utils

**Comment by ericnewcomer** [comment]
Oh so much better. Nice work @norkans7.

**Pull request merged**
