### PR TITLE
Replace channel specific perms with a single claim permission

### PR DESCRIPTION
**Pull request by rowanseymour**
Because they're not very useful and kind of annoying to maintain. 

There's probably a case for deployments being able to configure which channel types they support, but user permissions isn't the best solution for that.

### CODE REVIEW

**Comment by nicpottier** [comment]
Is there something else driving this apart from the config file being big? Doesn't seem like that is a thorn for us and I could definitely see deployments finding it useful to turn off particular channel types.. just trying to figure out what the motivation is here.

**Comment by rowanseymour** [comment]
My thinking is that it's useful to decouple core channel stuff from all the different channel types - and make each type as self-contained as possible - similarly to what we've done in Flowbase. Long term channels won't have handlers, but each type would still have:
- a way to generate an icon+summary for the claim page
- a way to generate a UI for claiming a channel of that type
- a (?) to handle activating and deactivating channels of that type (e.g. setting up callbacks)

Also no more database migrations every time someone adds a channel type.

To be clear we're not currently using permissions consistently in a way that would allow a deployment to turn them on and off - only a few channels on the claim page are hidden behind perms. If we actually want to allow deployments to turn off certain channel types, it would be cleaner if they could do it via a single setting, e.g. `DISABLE_CHANNEL_TYPES = (...)` similarly to how it might be done on the Courier side.

**Comment by nicpottier** [comment]
Seems to me permissions are the logical way to switch these on or off. Say you want the way of having another config setting for which channels are supported then you'd write some kind of mixin for the channel claim views to check that, which all seems like just another way of representing the permissions themselves.

Migrations are caused by the choices field on ChannelType aren't they? Nothing to do with permissions I don't think.

**Comment by nicpottier** [comment]
Also note that I support and agree completely with the goals you laid out, just that I'm not so confident removing permissions for channels makes sense.

**Comment by rowanseymour** [comment]
Not sure I agree that permissions are the correct way to model that - if a deployment doesn't support a channel type - then it's not a user-level permission they want, but a global way of turning off that channel type. And ideally they can make that change without running migrate to rewrite the permissions table.

I was also envisaging a claim page which dynamically lists channel types so it would be responsible for determining whether a channel type is allowed. In that scenario it's easier to check if a type is enabled rather than lookup the permission for that type and then check the permission. Same scenario if we have a single claim page which dynamically loads different forms based on channel type.

Migrations are caused by the choices field - mentioning that as a separate issue I'd like to improve.

**Comment by nicpottier** [comment]
Ok, go for it. I disagree but it is your call.

**Pull request merged**
