### PR TITLE
Added Channel.bod

### PR DESCRIPTION
**Pull request by rowanseymour**

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Feel like there should be a setter that does a dumps and a test to enforce the contract that these are json blobs.

**Comment by nicpottier** [comment]
Is bod a blob? I thought it was anything you wanted. In this case I think we really don't want it to be a blog as then you have crazy race issues etc..

**Comment by rowanseymour** [comment]
By blob we mean dict? Upside of dict is that it's easier to stuff another value in there if the need arises. But yeah race issues could be significant since this is a field we'll now be writing to after every message is received.

**Comment by ericnewcomer** [comment]
Or force that it's dict and only let you write one key at a time instead of the entire dict

**Comment by rowanseymour** [comment]
Writing one key at a time is the problem though no? You have to load the existing dict, update, then write the dict.

**Comment by nicpottier** [comment]
Right, ya, my bias would definitely be to keep this a simple string. We have config() for other shite.

**Comment by rowanseymour** [comment]
Technically this is a bag... but yes we should implement it as a string

**Comment by ericnewcomer** [comment]
Right, was just saying it would help with consistency issues. I guess this is "brief" optional data after all. So a single char is fine. If we used this for a bunch of stuff there's a bigger issue at hand.

**Comment by rowanseymour** [comment]
Just a text field now so we all good ?

**Comment by nicpottier** [comment]
doit

**Pull request merged**
