### PR TITLE
feature/two factor authentication

### PR DESCRIPTION
**Pull request by hudsonbrendon**
Hello guys, as discussed in the issue https://github.com/rapidpro/rapidpro/issues/1083

I am sending this PR with the proposed solutions. Below are screenshots of the pages for a better understanding of the flow.

After login, the user is redirected to this page:

After accepting the activation of two-factor login, the next page is displayed:

By clicking next, the user is redirected to the page where the QRCODE is generated:

In this step, the user must use an application such as Google authenticator, and inform the code generated in the form field.

After authentication, the screen below will be displayed to the user:

Org administrators have the possibility to activate two-factor login for other users. I added a new session in the administrative part of the orgs:

The page below displays all users in an organization. The administrator can enable two-factor login for one or more users.

It is also possible to generate backup tokens. These tokens can be used if the user loses access to their Google Authentication account or any other app used to generate the token.

The user must save the tokens generated on this page in a safe place. They will be used in a time of need.

The entire implementation is based on the application https://github.com/Bouke/django-two-factor-auth.

I had to overwrite some views to support some details of rapidpro. All the logic regarding the two-factor login is present in the app authentication.

Thanks.

### CODE REVIEW

**Comment by matmsa27** [comment]
Hi @nicpottier and @rowanseymour , how are you? I hope are you fine. Can you give us something update about this PR?

Thanks a lot for your attention and support.

**Comment by ericnewcomer** [comment]
Wow, there's a lot going on here. Right off, the biggest issue I see here is this PR is doing way too much, we should bite this off in logical pieces, we always aim first for an MVP for new features and iterate from there. The UX should also be more tightly integrated within RP, not leveraging third-party app views. 

To address this, I recommend the following..

Add a formax section to the account page for all users (not just admins). This section will give the option to enable 2FA if not currently enabled. If they click enable, it expands to show the QR code / code entry. Once that is completed, the formax collapses showing it as 2FA enabled. Expanding it while enabled shows the backup tokens and an option to disable 2FA. this means the 2FA UI is handled entirely from within the formax widget and the UI is minimal.

For this first bit, we do not need to prompt / force the user into 2FA and orgs admins do not control whether it is enabled / forced upon the user. Users can belong to more than one org so that notion would need further consideration. For an MVP, this is also not necessary.

Also, any templates should be written in haml. While I haven't looked at the django app here, my gut is that we should instead maybe be using a library for QR codes, tokens, etc, but certainly don't want/need anything that provides the views / pipeline for this since we want it to fit in with the rest of RP.

**Comment by matmsa27** [comment]
Hello @ericnewcomer , thanks a lot for your response and the feedback. This is very important to us. We agree with change requests that you commented on and the new approach, we believe that makes all sense have a UX more simple and put all responsibilities in a unique place.

To open pull requests flows, can we ask a question? For this adjust, the idea is to open a PR first with only the flow for UX with mocked data for example? Or, can we open the PR with adjustments suggested and the implementations from backend already integrated?

The next steps are?

1 - Remove the django-authentication library and use only django-otp library. The [django-otp library](https://django-otp-official.readthedocs.io/en/stable/) works with QR codes generation, 2FA process to use the TOTP protocol.

2 - Create a formax inside Org section for the user to configure the 2FA. All users can have access to this formax, referent on him user of course. And all users can enable or disable the 2FA to his user.

3 - Implement rules inside the formax to 2FA according to that you mentioned in the last message. If the 2FA is disabled, must show a button inside the formax to enable the 2FA, and when the user clicks on this button, the QR Code and a field to put the code generated by device application must show. If the 2FA is enabled, must show two buttons. The first button to show backup tokens, and when user click on this button, a new page must load listing the backup tokens. And the second button to disable 2FA to the user.

4 - Implement all templates related to this PR in haml.

Can we go ahead with this approach?

Thanks a lot for your attention, Eric.

Regards.

**Comment by ericnewcomer** [comment]
@matmsa27 yes, totally agree. We absolutely encourage discussion / mockups on approach before work begins.

I'd agree with those next steps except that I'd like to see the backup codes rendered when the formax is expanded after enabled for an account (instead of that being a dedicated page).

**Comment by hudsonbrendon** [comment]
Hello @ericnewcomer, the mockups of the screens are attached.

Org home:

home

Generate token:

token

Generate Backup Token:

Disable

I was wondering if you have any suggestions or if we can already start developing them?

**Comment by matmsa27** [comment]
Hi @ericnewcomer , according to the last comment, we already the UX done. Do you suggest any changes? 

If its ok, can we move on to the implementation and open a PR?

Regards.

**Comment by ericnewcomer** [comment]
Any reason we can't generate the tokens when it is enabled and just show them when the expand the formax when it has been enabled?

**Comment by matmsa27** [comment]
Hi Eric,

did you mean about backup tokens right?

Do you agree that backup tokens must be generated when user activate the 2FA, and when the 2FA is enabled and the user open the formax, the backup tokens must show inside the formax, dont need the user click on the backup tokens button to redirect another page?

The button for backup tokens shouldn't exists right?

Was your doubt related to that?

Thanks Eric.

**Comment by ericnewcomer** [comment]
Correct. The only UI should be within the formax itself and the user should never need to generate backup tokens manually. Only thought there is if they need to generate new ones once these are spent. So that case will need to be handled I imagine. I would still think they could just click a button and do that inline in the formax.

**Comment by matmsa27** [comment]
Hi @ericnewcomer , sorry for delay.

Nice, I got it. So, the backup tokens will be generated automatically when user enable the 2FA, and are available on formax. But the button for generate backup tokens must exists for user generate manually when backup tokens was use, right?

Thanks Eric.

**Pull request closed without merging**
