### PR TITLE
Android api

### PR DESCRIPTION
**Pull request by norkans7**
Adds endpoints to support the Android surveyor client.

Updated endpoints:
* Authenticate
* Org details
* Posting flow steps
* Fetch boundary aliases
* Flow definition

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Alright, this puppy needs to get back on master. Though dropping 0.07% in coverage sure is giving it a bad wrap!

**Comment by nicpottier** [comment]
I'm good with this, only comment would be to put ALPHA on the API pages and that they are liable to change in the future, no guarantees etc..

**Comment by ericnewcomer** [comment]
None of them are currently documented. Should we surface any of them? I know somebody was asking for flowdefinition access. Maybe just that one for now with a disclaimer?

**Comment by nicpottier** [comment]
Oh right.. Ya, the random other U-Report web and app folks need both a definition endpoint and the way of submitting steps, though I think we still keep scary ALPHA on there.

**Pull request merged**
