### PR TITLE
add flag on ActionLog to know is we escape links

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by ericnewcomer** [comment]
What about following the django naming and calling this "safe"

https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#std:templatefilter-safe

Or maybe, "html_safe"

Thoughts?

**Comment by norkans7** [comment]
Initially we added escape because the simulator was being broken  by tags in the messages or action logs.

In this case I found we have only the action logs from the webhook need to be safe. On the other hand we can have action logs for send email that might be broken if we use html_safe since they might be referencing one of the messages with the tags. I ended up implementing the flag my self.

Repro case: on the group chat
first msg: "CU001"
second msg: "</div> hello word"

**Comment by ericnewcomer** [comment]
I'm just referring to the name of the property

**Comment by nicpottier** [comment]
This feels a little weird to me overall. Wouldn't it be clearer to just say that the ActionLog is always HTML escaped, and if the caller wants a version that isn't then they can unescape it themselves? Having it be conditional seems overly complicated.

Would that work Norbert?

**Comment by norkans7** [comment]
Right Eric, I realize now has_link is not good enough I can rename that

**Comment by norkans7** [comment]
Nic, I think that's somehow similar to what is there... I added the field because on the simulate view we cannot tell which action log is which we just use their creation date and other them in combination with the messages. I thought adding the field was the way to tell when we have to escape or when we do not

**Comment by ericnewcomer** [comment]
Maybe we should just avoid putting user-entered text in the ActionLog and never escape it.

**Comment by ericnewcomer** [comment]
Now that IVR is shown in messages, I can't think of a reason why we need to put user-supplied text in the log.

**Comment by norkans7** [comment]
what about action logs like for the EmailAction https://github.com/nyaruka/rapidpro/blob/simulator_url/temba/flows/models.py#L3406

we do not include the message?

**Comment by ericnewcomer** [comment]
I'm fine with that.

**Comment by nicpottier** [comment]
I don't think we want to remove showing user supplies messages, certainly makes it much harder to debug cases where you are sending a message to someone else and that is a particularly burdensome scenario to test with real devices.

At the time that we add action logs, we know what parts are user supplied and which are not, so we should be able to encode the parts that are user supplied and not escape the rest. The key is to do the escaping at the time that we create the ActionLog element as that is the only time we can differentiate which parts are user supplied and which are not.

But I don't think we want a flag on the entire ActionLog, rather we just need to set a policy that anything in the ActionLog should be "safe", that is any HTML in it should be ok for us to just echo out to the user.

So for the cases of echoing user messages, we just need to make sure that the portion of that action log that is user supplied (the email or msg content) are escaped when building the ActiongLog object.

**Comment by norkans7** [comment]
Yep I think that make sense.

**Comment by nicpottier** [comment]
So this can be closed right?

**Comment by norkans7** [comment]
yep

**Pull request closed without merging**
