### PR TITLE
Recipients UI fixes

### PR DESCRIPTION
**Pull request by norkans7**
Remove bug fixes from https://github.com/nyaruka/rapidpro/pull/3091

### CODE REVIEW

**Comment by norkans7** [comment]
Flow Start Log 2020-11-20 17-22-05

**Comment by norkans7** [comment]
I believe this PR fixes https://github.com/rapidpro/rapidpro/issues/1387 as we always use 
`-include "includes/recipients.haml"` both on triggers page and flows starts page

**Review by rowanseymour — APPROVED** [review]
What about URNs?

**Comment by norkans7** [comment]
We display the matched/created contacts or the query for searches

**Review by rowanseymour — APPROVED** [review]

**Comment by ericnewcomer** [comment]
That contact icon should be the same color as the other icons.

**Pull request merged**
