### PR TITLE
Email URNs

### PR DESCRIPTION
**Pull request by ericnewcomer**
First step in allowing "user as contact" in Surveyor.

* Add mailto scheme support for ContactURN
* Allow creation of URNs when editing contacts
* Move contact field editing to its own dialog
* Show email urns (linked with mailto)
* Link twitter urns to twitter profile
* Add coverage for contacts/views.py and contacts/models.py

Relevant screen shots:

### CODE REVIEW

**Comment by nicpottier** [comment]
Wonder about the wording "Connection".. trying to think of other options.. obviously internally these are Universal Resource Names, which isn't great. What do we think about "Address"? Also, should we tweak this now that we know we DO have a priority field on ContactURN to allow sorting these a bit, would just be a UI tweak.

**Comment by ericnewcomer** [comment]
Struggled with the naming. Agree connection isn't great. Address for phone number, which is the common case, feels even worse to me though.

**Comment by nicpottier** [comment]
True.. I guess connection is ok..

**Comment by ericnewcomer** [comment]
Added ordering for URNS:


Note that all calls to Contact.update_urns(..) now assumes the supplied order is the preferred order.

**Comment by nicpottier** [comment]
Beautiful!

**Comment by ericnewcomer** [comment]
:see_no_evil:

**Pull request merged**
