### PR TITLE
Add brand field on Org

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
This looks to be missing setting the brand on Join actions..

**Comment by norkans7** [comment]
those look to me like update views

**Comment by nicpottier** [comment]
I'm talking about the view used when a new user signs up. You changed the "Grant" view, but that isn't the same one. You need to explicitly set the brand on that view (as you do on Grant) instead of having it just default to the hostname.

**Comment by norkans7** [comment]
Signup is extending Grant, I think that is enough, 
which default hostname are you mentioning?

**Comment by nicpottier** [comment]
Oh, right you are, was confusing Signup and Join.. doh.

**Pull request merged**
