### PR TITLE
temba components css latest styles

### PR DESCRIPTION
**Pull request by susanm74**

### CODE REVIEW

**Comment by susanm74** [comment]
@ericnewcomer FYI i directly copy/pasted https://github.com/nyaruka/temba-components/blob/main/static/css/temba-components.css, not sure if there are any extra steps or checks, but figured i'd get the ball rolling so that i know what needs to be done for the next time this needs to be done

**Comment by ericnewcomer** [comment]
The styles for rapid are a bit different than the components repo. We don't want to just blanket update these. i just wanted to make sure we had values for the new variables you added. Did any of these change as part of your work or is this just a diff to get them the same?

**Comment by ericnewcomer** [comment]
Ah missed your comment. We don't want to full sale copy these. Maybe we should get them in sync, but that'll be more delicate. More likely going the other direction (save for any recent additions).

**Comment by susanm74** [comment]
@ericnewcomer ah ok, if it's more delicate, then maybe something that's just easier and quicker to do together once the first time, if you have some time your thurs pm/my fri am (or if it can wait until our call next tues/wed)

**Pull request closed without merging**
