### PR TITLE
Modax Component

### PR DESCRIPTION
**Pull request by ericnewcomer**
* Add Modax component
 * Update gear links to trigger a modax purely through config
 * Easy modax triggering with button with only markup
 * Use on campaign create button and edit gear link
 * Add annotation flag for component fields so they can be responsible for label, help text, and errors (though currently this is styled as existing styles)

This includes https://github.com/nyaruka/rapidpro/pull/2619 as well, so merging that first might help reviewing this.

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Screen Shot 2019-11-26 at 3 45 33 PM

Screen Shot 2019-11-26 at 3 45 43 PM

**Comment by nicpottier** [comment]
Looks good but shall we push this to staging so everyone can do a run through and help on the QA front?

**Comment by ericnewcomer** [comment]
Okay, this is up on staging. From a visual standpoint, keep in mind the only things visible using new stuff are:

 * Campaign create dialog via button
 * Campaign edit dialog via gear links
 * Create campaign button itself
 * Errors from form validation failure

It shouldn't look dramatically different, but there are subtle differences, which I think I'm okay with as I work through these (the buttons are flatter, the labels aren't as heavy, some other minor tweaks).

**Comment by nicpottier** [comment]
Looks sweet, like the roll down treatment!

**Comment by nicpottier** [comment]
One thing that looks a bit different and maybe that I prefer in the old version is that on submission of the form we don't hide everything and show the balls.. those only appear when first showing the form content. It may be a bit nicer to not collapse the dialog on submission so that it appears a bit more fluid in case there are validation errors in the form.

**Comment by ericnewcomer** [comment]
Pretty sure we hide the controls, I think maybe the old world just has a
min height. I think I might agree that perhaps leaving them is nicer
though, was just mimicking the old stuff.

**Comment by nicpottier** [comment]
Hrmm, I was comparing with flow creation dialog but maybe that's not modax?

**Comment by rowanseymour** [comment]
I like the styling tho would say..

1. It is different to other dialogs like Start Flow.. which is not a problem if the plan is to convert them over very soon. But it is noticeable different in things like the Cancel button
2. I know I have my screen resolution set to "teeny-weeny font mode".. but that help and placeholder text is getting pretty hard to read

**Comment by rowanseymour** [comment]
For comparison.. and also me checking that it's not my screen resolution that's the problem..

Captura de Pantalla 2019-12-02 a la(s) 10 09 07

**Comment by ericnewcomer** [comment]
Am tweaking the submission behavior above re: @nicpottier, will bump the help text, was trying to get close to what was there, but maybe did a poor job of it.

**Comment by ericnewcomer** [comment]
To address comments:
Screen Shot 2019-12-02 at 3 50 19 PM

**Comment by ericnewcomer** [comment]
Pushing to staging @nicpottier @rowanseymour

**Comment by rowanseymour** [comment]
Captura de Pantalla 2019-12-03 a la(s) 12 07 26

Old vs new... the dropdown looks way nicer.. but I still think we need to up the contrast a bit.. I find myself straining a little to read the new modax.

**Comment by nicpottier** [comment]
Miss the icon too in the upper left corner!

**Comment by ericnewcomer** [comment]
Man that help text to me looks the same color and is bigger in the new version. Not sure which pixels you are asking me to push there. The label weights or the input text?

Was hoping to punt on icons until refresh since I wanted those to be pulled from the component icon set. Can look at an interim solution there if you feel strongly about them.

**Comment by rowanseymour** [comment]
@ericnewcomer the help text is the same.. but the labels and inputs themselves are lighter.. and harder to read. I really wish I could see your screen right now!

**Comment by ericnewcomer** [comment]
I thought your concern was the help text, that helps. 

Really don't see an issue here (even looked at both ends of the resolution spectrum). I can have another pass to try to make it as much like the old stuff as I can. Personally don't like the bold labels though, but 🤷‍♂. We need to remember this isn't a styling push, goal is just feature parity.

**Comment by rowanseymour** [comment]
It's possible it's me and my screen so would be helpful to hear from others before I book an appointment with an optician.

The other place I've noticed things get harder to read is the placeholder/hint text...

Captura de Pantalla 2019-12-03 a la(s) 13 19 02

(the second dropdown in each screenshot)

**Comment by ericnewcomer** [comment]
Placeholder text is same as help text, only bigger. I thought you were okay with the help text?

**Comment by rowanseymour** [comment]
Well if we were re-styling I'd argue we up the contrast on everything but I appreciate you're just trying to match the existing stuff. What I mean was that placeholder texts relatively got harder to read.. as illustrated by the modal below with an old and a new input..

Captura de Pantalla 2019-12-03 a la(s) 13 57 05

_Hi @contact!_ is very faint on my screen

**Comment by ericnewcomer** [comment]
Ya, that should be darker for the controls in this PR.

**Comment by ericnewcomer** [comment]
I think maybe your readability concerns might go away when we switch to a weighted font. For example, the current default component styling uses one and looks like this:

Screen Shot 2019-12-03 at 11 07 20 AM

However, we are overriding a variety of those things (including font) to match the current bootstrapped site. If the above looks okay to you, I'd like to shelve these until we style for real since I feel this PR is good enough until then.

**Comment by ericnewcomer** [comment]
Screen Shot 2019-12-03 at 11 43 44 AM

I one hundred % agree this is worse, but here it is styled for our current fonts.

**Comment by ericnewcomer** [comment]
Screen Shot 2019-12-03 at 12 01 36 PM

Actually, here's a third option using a slightly different but very close font without any interpolation which I think is the best interim option.

**Comment by ericnewcomer** [comment]
Mergey merge?

**Pull request merged**
