### PR TITLE
Show media for MMS in simulator

### PR DESCRIPTION
**Pull request by norkans7**
Addresses https://github.com/rapidpro/rapidpro/issues/496 and https://github.com/rapidpro/rapidpro/issues/495

mms-simulator

### CODE REVIEW

**Comment by nicpottier** [comment]
Can you push this to staging so we can play with it?

**Comment by norkans7** [comment]
This branch is pushed

**Comment by ericnewcomer** [comment]
How bout we remove the icons since we are showing real previews?

**Comment by norkans7** [comment]
new_sim_media_show

**Pull request merged**
