### PR TITLE
Allow the target_urls of incident notifications to differ by type

### PR DESCRIPTION
**Pull request by rowanseymour**
Currently the target_url for notifications for incidents is just the incident list page... but it makes more sense that if you click on a channel disconnected incident notification.. it takes you to the channel read page, and viewing that page is what clears the notification.

### CODE REVIEW

**Comment by norkans7** [comment]
What if the user visit the page before seeing the email the notification is also marked as seen?

**Comment by rowanseymour** [comment]
@norkans7 yes... I do wonder if I've made this more complicated than it needs to be... another approach would be that the link for the notification, whether from the UI or an email, is a redirect that marks it as seen when you click on it. Hard to evaluate tho when notifications still don't exist in the UI @ericnewcomer

**Comment by norkans7** [comment]
I think it would be best to send the incident read view and that is the one that will redirect to the channel page and make the notification seen.

Currently if the user just visits the channel page the notification will be marked as seen.

I think moving to notification marking as seen to the incident view that then redirects to the channel page is probably less confusing.
But we can adjust that later after using the current in the UI and see exactly how that happens

**Comment by rowanseymour** [comment]
@norkans7 we don't actually have an incident read view.. just a list which isn't an ideal target URL

**Pull request merged**
