### PR TITLE
📱 Add support for `Msg.TYPE_TEXT(T)` to be used (for now) for outgoing messages

### PR DESCRIPTION
**Pull request by rowanseymour**

### CODE REVIEW

**Review by norkans7 — APPROVED** [review]

**Review by ericnewcomer — APPROVED** [review]
We need to change the flow message filter before changing this though

**Comment by rowanseymour** [comment]
@ericnewcomer this and the related PRs are just to start using it for outgoing messages

**Comment by ericnewcomer** [comment]
Just saying that step one is probably changing the flow filter to look at flow_id instead of msg_type is all

**Comment by rowanseymour** [comment]
But that's just incoming messages.. we're talking about the inbox views no?

**Comment by ericnewcomer** [comment]
Oh i guess that's true. man, honestly it's such a weird filter to begin with.

**Pull request merged**
