### PR TITLE
Added migration for flow run indexes

### PR DESCRIPTION
**Pull request by rowanseymour**

### CODE REVIEW

**Comment by nicpottier** [comment]
Yarp.. will ship these tonight and trigger them on TextIt in the background.

**Comment by rowanseymour** [comment]
Shame CREATE INDEX IF NOT EXISTS wasn't a thing as that would be marginally simpler than remembering to fake this on rapidpro

**Comment by nicpottier** [comment]
These have been created..

Wonder if we could use the DO hack here:
  http://dba.stackexchange.com/questions/35616/create-index-if-it-does-not-exist

To have this migration properly detect that it is missing and only add them in those cases.

**Comment by rowanseymour** [comment]
Updated using that DO hack. Roll on Postgresql 9.5 and CREATE INDEX IF NOT EXISTS

**Pull request merged**
