### PR TITLE
RocketChat ticketer

### PR DESCRIPTION
**Pull request by koallann**
Addition of the RocketChat ticketer as discussed [here](https://github.com/rapidpro/rapidpro/issues/1251).

RocketChat provides an app framework to extend its functionalities, so we used that to implement this integration. The application is in release candidate v1.0.0, suggestions are welcome, see:

https://github.com/Ilhasoft/Rocket.Chat.App-Tickets/tree/release/v1.0.0

### CODE REVIEW

**Comment by koallann** [comment]
PR on Mailroom: https://github.com/nyaruka/mailroom/pull/333

**Comment by matmsa27** [comment]
Hi everyone, how are you? Any news about the new ticketer rocketchat type on Rapidpro? 

Thank you so much, we are available to improve this, and suggestions are welcome on our application.

**Comment by nicpottier** [comment]
Hey hey. Sorry we are a bit swamped right now as we button up the redesign this week. We'll take a deeper look at this next week, but  we are excited about it for sure!

**Comment by matmsa27** [comment]
Hello everyone, we are very excited to improve this and discuss other points about Ticketer Service and RocketChat Ticketer on Rapidpro. 

Do you have any news about this PR and mailroom? We are open to receive suggestions on our app to RocketChat available [here](https://github.com/Ilhasoft/Rocket.Chat.App-Tickets/tree/release/v1.0.0) too.

**Comment by matmsa27** [comment]
Currently, the RocketChat ticketer receive the requests to a new message and when the ticket status changed. 

To improve in the future, the RocketChat ticketer can receive a request for:
- when the conversation forwarded to another agent inside the RocketChat instance
- when the conversation was created but is queued to an agent to get the conversation.

**Comment by matmsa27** [comment]
Hi @nicpottier , how are you? We are very excited and to see you improvements suggestions on this PR and on our [RocketChat app](https://github.com/Ilhasoft/Rocket.Chat.App-Tickets/tree/release/v1.0.0). Please, when you available, can you review our PR? Thank you

**Comment by rowanseymour** [comment]
Replaced by #3071

**Pull request closed without merging**
