### PR TITLE
Fix flow label delete

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
More changes needed on this

**Comment by norkans7** [comment]
Flows 2020-11-18 23-51-31
Flows 2020-11-18 23-51-14

**Comment by norkans7** [comment]
Ready

**Comment by ericnewcomer** [comment]
_No way to undo this operation._ We are such programmers.

**Comment by ericnewcomer** [comment]
It should just read, "This cannot be undone"

**Review by rowanseymour — APPROVED** [review]

**Pull request merged**
