### PR TITLE
Deploy: Management command for applying migrations manually

### PR DESCRIPTION
**Pull request by rowanseymour**
Supports any migration module with a `def apply_offline()` function.

* Same syntax as migrate, makemigrations etc
* Can reference migrations by prefix, e.g. "msgs 0023"
* Detects any migration conflicts or if migration has already been applied
* Setting verbosity > 1 enables timing of migration (e.g. "-v 2")

screen shot 2016-11-23 at 11 51 06

### CODE REVIEW

**Comment by rowanseymour** [comment]
I suppose 'offline' isn't the right term here - we're actually applying migrations.. online or concurrently. Suggestions?

**Comment by norkans7** [comment]
'async'

**Comment by ericnewcomer** [comment]
Do we want to fake second? Seems the more common case is a long running data migration in which case we want to mark it as faked first so that we can happily keep pushing code while it goes about its business. 

I know it's not technically offline, but honestly I don't have any problem with that name. If you want to change it, maybe something like migrate_manually, though I'm okay with something like migrate_concurrently too.

**Comment by rowanseymour** [comment]
@ericnewcomer good point. I've switched the order so faking comes first. On the name, I'll leave it as is unless anyone else objects

**Comment by nicpottier** [comment]
Fundamentally what we are doing here is reapplying a migration which the db already thinks was run. (either because it was faked previously or just ran) So ya, faking afterwards seems odd, I think almost by definition this should only work on a migration that has already run. (otherwise you might as well run the normal migrate)

So maybe it is something more like rerun_migration ?

**Comment by nicpottier** [comment]
The way we will use this is that we will do a deploy with `fake` which will fake all the migrations, then shell in, screen and run this command.

**Comment by rowanseymour** [comment]
@ericnewcomer @nicpottier updated so it's

* `./manage.py migrate_manual contacts 0043` to just run a migration manually (won't error if migration is recorded as applied)
* `./manage.py migrate_manual contacts 0043 --record` to run and record as applied (will error if migration is already recorded as applied)

And name of method required in migration is now `apply_manual`

**Pull request merged**
