### PR TITLE
Revert back to allow the contact list page send message button

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by rowanseymour** [comment]
This was removed in f39b9f0137bba7fcf218053a6e8e793067be32ef.. isn't there a new WC way of doing this? @ericnewcomer

**Comment by ericnewcomer** [comment]
I didn't see where on the contact list page allowed sending messages. Missed that reply button (even had trouble locating it a second time). For some reason that icon wasn't registering in my brain.

But ya, as Rowan said, this needs to be done with WC. You can look at how it's done on the message list page.

**Comment by norkans7** [comment]
I think the current button in WC does not support icons so I had added this to fix the prod.
I'll keep seeing changes needed to make that work

**Comment by ericnewcomer** [comment]
Don't understand why, I can have a look

**Comment by norkans7** [comment]
I think so far we expect a name https://github.com/nyaruka/rapidpro/blob/master/components/src/button/Button.ts#L174

**Comment by ericnewcomer** [comment]
Ah, yes buttons don't currently take icons, but you shouldn't need to use the WC button object to fix this.

**Comment by norkans7** [comment]
Correct, this PR just add back the missing JS code so that this old button works again 

https://github.com/nyaruka/rapidpro/blob/master/templates/contacts/contact_list.haml#L134

**Comment by ericnewcomer** [comment]
I'm saying you shouldn't need to revert this to make it work. I'll take this over.

**Pull request closed without merging**
