### PR TITLE
🧯 Fix choose org page

### PR DESCRIPTION
**Pull request by rowanseymour**
No org warning is always shown

Captura de Pantalla 2020-11-23 a la(s) 15 35 31

### CODE REVIEW

**Review by nicpottier — COMMENTED** [review]
classic

**Comment by rowanseymour** [comment]
@nicpottier 6.0?

**Comment by nicpottier** [comment]
blech.. I mean this seems as safe as any thing could be? Yes?

**Comment by rowanseymour** [comment]
well now that you've said that it's cursed to bring down production.. but I vote yes

**Pull request merged**
