### PR TITLE
Update to latest django-hamlpy and regenerate translation files

### PR DESCRIPTION
**Pull request by rowanseymour**
Currently our po files (last generated 6 months ago) don't include strings from haml files as makemessages wasn't be correctly patched to preprocess haml files. Not clear if this has ever worked.

Note that the regenerated po files here only include strings from this repo - not sure what we do about content in nyaruka/textit.

### CODE REVIEW

**Comment by norkans7** [comment]
@rowanseymour I think if you symlink the folder the make messages will include all the strings

**Comment by rowanseymour** [comment]
@norkans7 I was more wondering if those strings _belong_ in this repo or not

**Comment by norkans7** [comment]
Ahh I see

**Comment by nicpottier** [comment]
Looks good, need to these on transifex as well.

**Pull request merged**
