### PR TITLE
manage logins title repeated

### PR DESCRIPTION
**Pull request by susanm74**
removed block subtitle from org manage accounts template to prevent the effect of the "manage logins" title repeating due to the subtitle displaying the same text as the title

(couldn't figure how to link back to the task in the new interface space)

### CODE REVIEW

**Comment by rowanseymour** [comment]
Have you checked what this does when in the old interface? There we currently show the org name as the title and "Manage Logins" as the subtitle, but I think in both cases we can get rid of the subtitle, and have the old interface as "Manage Logins" as its title.

Captura de Pantalla 2022-08-08 a la(s) 09 52 15

**Review by ericnewcomer — APPROVED** [review]

**Comment by susanm74** [comment]
AFTER
Screen Shot 2022-08-08 at 11 28 41 PM

**Comment by rowanseymour** [comment]
@susanm74 assuming didn't see my comment above re the old UI

**Comment by ericnewcomer** [comment]
@susanm74

**Comment by susanm74** [comment]
@rowanseymour so sorry, just saw these now, i think i updated my github email notifications on thurs or fri last week, so any changes or comments on PRs that i'm a participant of should now hit my inbox and i shouldn't anything those going forward!

**Pull request merged**
