### PR TITLE
Improve contacts import

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
What about case of phone numbers that aren't E164?

**Comment by nicpottier** [comment]
Test for number case?

**Comment by norkans7** [comment]
Adding one

**Comment by norkans7** [comment]
phone numbers that aren't E164 always import using the country code of the channel.

Now this make sure for each import we show all the errors even if no record was created

**Comment by nicpottier** [comment]
nice

**Pull request merged**
