### PR TITLE
👰🏾 Fix .travis.yaml - compilemessages check

### PR DESCRIPTION
**Pull request by dodobas**

### CODE REVIEW

**Comment by nicpottier** [comment]
Hrmm.. I don't think this is right. `.mo` files are binary, they are never going to show a line count diff here. Are you sure you checked in your new `.mo` files after you rebuilt them? Those were in `.gitignore` so would be an easy thing to do.

**Comment by dodobas** [comment]
yes, sure ... .po and .mo files were checked in ... https://github.com/nyaruka/rapidpro/pull/2390/files?file-filters%5B%5D=.mo&file-filters%5B%5D=.po

**Comment by nicpottier** [comment]
If I pull your branch and do compile messages then I get changes in the `.mo` files.

It looks like you didn't run `compilemessages` after your last `makemessages` as the dates are different.

Your current `locale/en_US/LC_MESSAGES/django.mo` file:

```
Project-Id-Version: PACKAGE VERSION
Report-Msgid-Bugs-To:
POT-Creation-Date: 2019-06-13 20:48+0000
PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE
Last-Translator: FULL NAME <EMAIL@ADDRESS>
Language-Team: LANGUAGE <LL@li.org>
Language:
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
```

After a rebuild:
```
Project-Id-Version: PACKAGE VERSION
Report-Msgid-Bugs-To:
POT-Creation-Date: 2019-06-18 09:09+0000
PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE
Last-Translator: FULL NAME <EMAIL@ADDRESS>
Language-Team: LANGUAGE <LL@li.org>
Language:
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
```

You PO files have the latter date in them.

**Comment by nicpottier** [comment]
Closing as I'm pretty sure current code is right, feel free to reopen if you find otherwise.

**Comment by dodobas** [comment]
i was blindly following steps in `.travis.yml` where `compilemessages` is executed before `makemessages` ... i guess it has to be the other way around :)

**Comment by nicpottier** [comment]
Ah, that might be it, maybe add a comment there to help the next one. Has to happen in that order because the `makemessages` changes the PO file date which then would cause all `mo` files to be different. Doing compile first lets us check that `mo`->`po` is up to date, then `makemessages` makes sure that `python`->`po` is right.

**Pull request closed without merging**
