### PR TITLE
Add infinite loop dialog

### PR DESCRIPTION
**Pull request by ericnewcomer**
Show a dialog when infinite loops are detected on dropping connections.

### CODE REVIEW

**Comment by nicpottier** [comment]
Are tests possible for this case?

**Comment by ericnewcomer** [comment]
Probably not without a big refactor. We'll get there, but not yet.

**Comment by nicpottier** [comment]
FINE

**Comment by ericnewcomer** [comment]
FINE!

**Comment by ericnewcomer** [comment]
Putting this in the language fixes branch since I've done the work to add tests for this.

**Pull request closed without merging**
