### PR TITLE
Feature/support to russian language

### PR DESCRIPTION
**Pull request by hudsonbrendon**
Hello guys, as discussed in the issue rapidpro#1202
follows the PR that adds the Russian language to rapidpro.

### CODE REVIEW

**Comment by matmsa27** [comment]
Hi everyone, do you have any news about this PR?

**Comment by rowanseymour** [comment]
@matmsa27 this PR doesn't seem correct.. there are arbitrary changes in the `es` locale and it's missing the settings changes... closing in favor of #2814

**Comment by matmsa27** [comment]
Hi @rowanseymour , ok. Thanks for the changes and feedbacks. This already on Transifex to start the strings translation?

**Comment by rowanseymour** [comment]
Yes, I've merged to rapidpro/rapidpro and setup Russian in Transifex

**Comment by matmsa27** [comment]
Thanks a lot Rowan.

**Pull request closed without merging**
