### PR TITLE
Add link for flow for flow actions

### PR DESCRIPTION
**Pull request by norkans7**
https://github.com/rapidpro/rapidpro/issues/507

### CODE REVIEW

**Comment by nicpottier** [comment]
screenshot?

**Comment by norkans7** [comment]
flow-link

**Comment by norkans7** [comment]
In other places clicking the action opens the editor,  is it okay breaking
that?

On Apr 3, 2017 6:25 PM, "Eric Newcomer" <notifications@github.com> wrote:

How about just making the flow name itself a link? I think that's a bit
more clear.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nyaruka/rapidpro/pull/1208#issuecomment-291195741>, or mute
the thread

**Comment by ericnewcomer** [comment]
Yes, I think in this case, if they click on the name it can go to the flow, but elsewhere on that action opens the edit dialog. The link should show an underline when they hover over it.

**Pull request merged**
