### PR TITLE
Added error and warning level action logging

### PR DESCRIPTION
**Pull request by rowanseymour**
Added warning level for actions that proceed despite expression errors (e.g. SaveToContact) and error level for actions that can't proceed (e.g. AddToGroup when group name is invalid). For example:

screen shot 2015-09-16 at 12 59 56

Checking how everyone feels about the general idea before adding more log events.

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Not wild about the colors, thinking maybe we might start rethinking the treatment for non-message alerts in the simulator. But I am totally behind the idea of surfacing this stuff to the user in the simulator.

**Comment by rowanseymour** [comment]
Yeah the warning isn't so easy to read. I thought about framing them but then they're not so distinguishable from the messages. Open to suggestions or if you wanted you could do the UI part.

**Comment by nicpottier** [comment]
Sweet! 

What's the difference between an error and a warning to the user?

**Comment by ericnewcomer** [comment]
Ya, thinking we probably don't need the error / warning distinction either.

**Comment by rowanseymour** [comment]
Warning means that there was an problem but the action proceeded regardless, e.g. for a `SendAction` or `ReplyAction` - if an expression can't be evaluated we send it anyway with the un-evaluated expression. I think `SaveToContactAction` would behave like this as well... though that's debatable.

Whereas error means that we can't proceed with the action - e.g. `AddToGroupAction` can't add someone to a group called @something because group names can't begin with '@', and `AddLabelAction` can't add a label that begins with '@'.

Even if we decide the distinction is unnecessary for users, I think it would be good for the flow engine to distinguish between the two and then we can just surface them both as errors.

**Comment by ericnewcomer** [comment]
Right, this is just from the user's perspective that the distinction isn't
worth the confusion.

**Comment by rowanseymour** [comment]
Ok if I update it to use the dark red text for both errors and warnings then that readable enough for now?

And thinking more about `SaveToContactAction` - it wouldn't be worst idea to borrow another idea from Excel and set the field value to something like "#ERROR" rather than the unevaluated expression.

**Comment by ericnewcomer** [comment]
While that seems fine in the simulator, I think I'd err towards the django template approach, ie, empty. Since these mistakes can be end-user facing (on cell phones), #ERROR would be really awful.

**Comment by nicpottier** [comment]
I think Rowan is talking about the case where we can't evalulate it, so we actually keep the expression there. We only replace with nothing when it is valid but the variable is missing and/or empty.

I actually prefer leaving the expression, I think for compound things where you might be substituting things in it is clearer than replacing everything with #ERROR

**Comment by ericnewcomer** [comment]
Ya, I realize that. Just wondering if replacing it with nothing might lead to less awkwardness with actual users. Hi @contact.nam! I think maybe my preference would be blank (though reporting it in the simulator), if not blank, then much prefer keeping it the way it is over #ERROR.

**Comment by ericnewcomer** [comment]
I guess that was a bad example.. oops. But same deal if that was a divide by zero or malformed expression.

**Comment by nicpottier** [comment]
Just tried it, looks like you are right @contact.nam just comes through. I guess if we are reporting these in the simulator as errors now then maybe blank IS better.. though partly we've echoed them out to deal with overlapping with Twitter stuff in the past as well.. 

Maybe it is best to hold off on that change until we change the expression format and add @@ escaping.

**Comment by nicpottier** [comment]
To wrap this up (which I think having this out there would be great) I'd say let's just make both RED for the time being and be done with it.

**Comment by rowanseymour** [comment]
Updated to use red for both warnings and errors

The error handling discussion deserves its own thread, so suffice to say for now that my gut feeling is that when it comes to assigning values to contact fields, and re-using them in subsequent expressions, it might be useful for `Value` to have some sort of error flag.

**Comment by ericnewcomer** [comment]
Looks good, this is a nice feature for sure.

**Pull request merged**
