### PR TITLE
Switch to sending UNICODE for HighConnection channels

### PR DESCRIPTION
**Pull request by nicpottier**
Switches to sending messages on the HighConnection channel as UTF-8.

plz glance at it someone. :)

### CODE REVIEW

**Comment by nicpottier** [comment]
@ericnewcomer @norkans7 @rowanseymour bueller?

**Comment by norkans7** [comment]
LGTM

**Comment by nicpottier** [comment]
Damn, norbert dropping new acronyms!

**Comment by nicpottier** [comment]
Thanks!

**Pull request merged**
